import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Link,useLocation}from'react-router-dom';
import'./styles.css';

const PHONE='512-363-6671', TEL='tel:+15123636671';
const areas={
 'san-marcos':{city:'San Marcos',eyebrow:'Made for life between the river and the ridge',title:'Simple tallow skincare in San Marcos, TX',text:'A warm, local skincare concept for neighbors who want fewer ingredients and a more intentional daily routine.',detail:'San Marcos customers balance sun, river days, air conditioning, and fast-changing Central Texas weather. This demo collection is positioned as a simple finishing balm for dry-feeling areas, with clear directions and Texas-heat storage guidance.',tips:['Use a pea-sized amount on slightly damp skin','Keep jars out of hot cars and direct sun','Patch-test every new skincare product first']},
 'kyle':{city:'Kyle',eyebrow:'Uncomplicated care for fast-growing Kyle',title:'Tallow skincare near Kyle, TX',text:'A short drive from San Marcos, with simple pickup and inquiry options represented for this prospect concept.',detail:'Kyle families need skincare that is easy to understand and easy to work into busy routines. This page emphasizes multi-use options, fragrance-free demo choices, and a direct route to ask what may fit a household.',tips:['Start small—a little balm goes a long way','Choose fragrance-free when scent is a concern','Ask a dermatologist about persistent irritation']},
 'new-braunfels':{city:'New Braunfels',eyebrow:'Hill Country care for sunny days and dry-feeling skin',title:'Tallow skincare near New Braunfels, TX',text:'Hill Country-inspired balm concepts presented with straightforward ingredients, use, and storage information.',detail:'Between river recreation, warm summers, and dry indoor air, New Braunfels shoppers often look for a compact balm for hands, elbows, and other dry-feeling spots. This demo page makes product expectations and safe-use reminders easy to find.',tips:['Apply after bathing to help seal in moisture','Store cool; natural balms may soften in heat','Stop use if irritation develops']}
};
const products=[
 {name:'Bare Hill Balm',tag:'Fragrance-free demo',use:'Face & dry spots',copy:'A stripped-back concept for shoppers who prefer no added scent.',tone:'oat'},
 {name:'Cedar & Clay',tag:'Lightly scented demo',use:'Hands & body',copy:'A grounded Hill Country-inspired concept for an evening routine.',tone:'cedar'},
 {name:'Little River Balm',tag:'Family-minded demo',use:'Simple multi-use care',copy:'A gentle-positioned concept with patch-testing guidance front and center.',tone:'sage'}
];
function Meta({title,description,path='/'}){useEffect(()=>{document.title=title;document.querySelector('meta[name="description"]')?.setAttribute('content',description);document.querySelector('link[rel="canonical"]')?.setAttribute('href','https://example.com'+path);window.scrollTo(0,0)},[title,description,path]);return null}
function Header(){const[open,setOpen]=useState(false);const l=useLocation();useEffect(()=>setOpen(false),[l]);return <><div className="utility">Serving San Marcos, Kyle & New Braunfels <a href={TEL}>{PHONE}</a></div><header><Link className="brand" to="/" aria-label="Texas Hill Country Tallow home"><span className="brandmark">TH</span><span>Texas Hill Country<small>Tallow · Demo Concept</small></span></Link><button className="menu" aria-expanded={open} aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>Menu</button><nav className={open?'open':''} aria-label="Main navigation"><a href="/#balms">Balms</a><a href="/#why">Why tallow?</a><a href="/#story">Our story</a><Link to="/areas/san-marcos">Areas</Link><a className="navcall" href={TEL}>Call us</a></nav></header></>}
function Footer(){return <footer><div><Link className="footerbrand" to="/">Texas Hill Country Tallow</Link><p>Prospect website demonstration for a fictional tallow skincare brand.</p></div><div><strong>Explore</strong><a href="/#balms">Demo balms</a><a href="/#faq">FAQs</a><Link to="/areas/san-marcos">San Marcos</Link></div><div><strong>Contact</strong><a href={TEL}>{PHONE}</a><span>123 Main St, San Marcos, TX</span><span>hello@example.com</span></div><p className="fine">© 2026 Texas Hill Country Tallow · All products, reviews, hours, email, and operational claims shown are fictional demo content. This site does not provide medical advice.</p></footer>}
function Jar({tone='oat',label='Hill Country'}){return <div className={'jar '+tone} role="img" aria-label={'Illustrated '+label+' balm jar'}><div className="lid"/><div className="jarbody"><span>Texas Hill Country</span><b>{label}</b><small>TALLOW BALM · DEMO</small></div></div>}
function Home(){
 const[notice,setNotice]=useState('');
 function submit(e){e.preventDefault();setNotice('Demo received—no information was transmitted or stored.')}
 const schema={"@context":"https://schema.org","@type":"LocalBusiness","name":"Texas Hill Country Tallow","description":"Fictional prospect website for tallow skincare in San Marcos, Texas.","telephone":"+1-512-363-6671","address":{"@type":"PostalAddress","streetAddress":"123 Main St","addressLocality":"San Marcos","addressRegion":"TX","addressCountry":"US"},"areaServed":["San Marcos","Kyle","New Braunfels"],"url":"https://example.com/"};
 return <><Meta title="Tallow Skincare in San Marcos, TX | Texas Hill Country Tallow" description="Explore a demo collection of simple Hill Country-inspired tallow balms in San Marcos, Texas."/><script type="application/ld+json">{JSON.stringify(schema)}</script>
 <main>
 <section className="hero"><div className="herocopy"><span className="eyebrow">Simple ingredients · Hill Country spirit</span><h1>Tallow skincare in <em>San Marcos, TX</em></h1><p>Less clutter on the label. More clarity in your routine. Explore a local demo collection inspired by old-fashioned simplicity and modern transparency.</p><div className="actions"><a className="button" href={TEL}>Call us now</a><a className="textlink" href="#balms">Explore demo balms →</a></div><small className="disclosure">Prospect concept: product availability and claims are fictional.</small></div><div className="herovisual"><div className="sun"/><Jar label="Bare Hill"/><span className="sketch">small batch<br/>concept</span></div></section>
 <section className="trust" aria-label="Concept values"><span><b>Short labels</b>Easy to understand</span><span><b>Local concept</b>San Marcos, Texas</span><span><b>Clear guidance</b>Use, patch test & storage</span><span><b>Direct contact</b>No complicated funnel</span></section>
 <section className="section" id="balms"><div className="heading"><span className="eyebrow">The everyday edit</span><h2>Three balms. Three simple starting points.</h2><p>Competitor research showed that shoppers want fragrance-free choices, multi-use care, and clear directions. These fictional products demonstrate that approach.</p></div><div className="productgrid">{products.map((p,i)=><article className="product" key={p.name}><div className="productart"><Jar tone={p.tone} label={p.name.replace(' Balm','')}/><span>0{i+1}</span></div><small>{p.tag}</small><h3>{p.name}</h3><p>{p.copy}</p><div className="productfoot"><b>{p.use}</b><a href="#contact">Ask about it →</a></div></article>)}</div></section>
 <section className="split problem" id="why"><div><span className="eyebrow">When skincare feels like too much</span><h2>Your shelf is crowded. Your skin still feels dry.</h2><p>Tallow shoppers are often looking for a simpler finishing step—not another ten-product routine. The concept starts with one small amount, transparent expectations, and no miracle language.</p><ul><li>Rich, occlusive texture designed to help seal in moisture</li><li>Multi-use positioning for hands, elbows, and dry-feeling areas</li><li>Honest caveat: tallow may not suit oily or acne-prone skin</li></ul></div><aside className="notecard"><b>Know before you try</b><p>Patch-test first. Stop if irritation occurs. Fragrance and essential oils can bother sensitive skin. Ask a qualified clinician about ongoing skin concerns.</p></aside></section>
 <section className="story" id="story"><div className="landscape"><span>San Marcos</span><b>29.8833° N</b></div><div><span className="eyebrow">A fictional local story</span><h2>Rooted in the rhythm of the Hill Country.</h2><p>Texas Hill Country Tallow is presented as a small San Marcos concept built around a useful idea: explain what is in the jar, what it feels like, and how to use it—without overpromising.</p><p>Its visual language draws from limestone, live oak, cedar, sun-warmed clay, and the quieter side of Central Texas.</p><div className="signature">Hill Country, made simple.</div></div></section>
 <section className="section process"><div className="heading"><span className="eyebrow">A clearer routine</span><h2>Start small. Notice how your skin responds.</h2></div><div className="steps"><article><b>01</b><h3>Choose</h3><p>Pick fragrance-free or a lightly scented demo direction.</p></article><article><b>02</b><h3>Patch-test</h3><p>Try a small area and wait before expanding use.</p></article><article><b>03</b><h3>Warm</h3><p>Melt a pea-sized amount between clean fingertips.</p></article><article><b>04</b><h3>Press</h3><p>Apply lightly to slightly damp skin where needed.</p></article></div></section>
 <section className="gallery"><div className="gallerycopy"><span className="eyebrow">Texture, context, care</span><h2>A gallery that explains—not just decorates.</h2><p>Each visual block gives customers useful context: expected texture, small application amount, and heat-aware storage.</p></div><div className="tile texture"><span>Whipped texture</span></div><div className="tile amount"><span>Start pea-sized</span></div><div className="tile storage"><span>Store cool & dry</span></div></section>
 <section className="review"><span className="quote">“</span><blockquote>The copy made the concept feel approachable. I knew what the balm was, how to start, and what questions to ask.</blockquote><p>— Fictional website-demo feedback; not a product testimonial</p></section>
 <section className="local"><div><span className="eyebrow">San Marcos, Texas</span><h2>Natural skincare curiosity meets practical local guidance.</h2></div><p>From hot parked cars to humid river days, Central Texas changes how natural balms behave. This concept addresses softening, storage, scent expectations, and patch testing before the customer ever needs to ask.</p></section>
 <section className="section areas"><div className="heading"><span className="eyebrow">Around the Hill Country</span><h2>Explore your area</h2></div><div className="areagrid">{Object.entries(areas).map(([slug,a])=><Link to={'/areas/'+slug} key={slug}><small>Local guide</small><h3>{a.city}, TX</h3><span>View area page →</span></Link>)}</div></section>
 <section className="faq section" id="faq"><div className="heading"><span className="eyebrow">Good questions, clear answers</span><h2>Tallow balm FAQs</h2></div><div>{[
 ['What does tallow balm feel like?','It is generally richer and more occlusive than a water-based lotion. Begin with a very small amount.'],
 ['Is this intended to treat eczema or acne?','No. This demo makes no treatment claims. Persistent or painful skin concerns belong with a qualified medical professional.'],
 ['Can acne-prone skin use tallow?','Tallow may feel too heavy for oily or acne-prone skin. Patch-test cautiously and seek professional advice when appropriate.'],
 ['Why can a natural balm soften?','Oil-based balms can soften in Texas heat. Keep the container cool, dry, and away from a parked vehicle or direct sun.'],
 ['Are these products really available?','No. The products, reviews, email, and business operations on this prospect site are fictional placeholders.']
 ].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 <section className="contact" id="contact"><div><span className="eyebrow">Start with a simple question</span><h2>Call or send a demo inquiry.</h2><p>This form demonstrates front-end behavior only. Nothing is submitted or stored.</p><a href={TEL} className="phone">{PHONE}</a></div><form onSubmit={submit}><label>Name<input required name="name" autoComplete="name"/></label><label>Email<input required type="email" name="email" autoComplete="email"/></label><label>What are you curious about?<select name="interest"><option>Fragrance-free balm</option><option>Multi-use balm</option><option>Local availability</option></select></label><button className="button">Send demo inquiry</button><div role="status">{notice}</div></form></section>
 <section className="map"><div><span>Map placeholder</span><b>123 Main St<br/>San Marcos, TX</b><small>Fictional street address supplied for this prospect demo</small></div></section>
 </main></>}
function Area({slug}){const a=areas[slug];const schema={"@context":"https://schema.org","@type":"Service","name":`Tallow skincare near ${a.city}, Texas`,"provider":{"@type":"LocalBusiness","name":"Texas Hill Country Tallow"},"areaServed":{"@type":"City","name":a.city},"url":`https://example.com/areas/${slug}`};return <main><Meta title={`Tallow Skincare Near ${a.city}, TX | Texas Hill Country Tallow`} description={a.text} path={'/areas/'+slug}/><script type="application/ld+json">{JSON.stringify(schema)}</script><section className="areaHero"><span className="eyebrow">{a.eyebrow}</span><h1>{a.title}</h1><p>{a.text}</p><a className="button" href={TEL}>Call {PHONE}</a></section><section className="areaBody"><div><span className="eyebrow">Local context</span><h2>A routine shaped around {a.city} life.</h2><p>{a.detail}</p></div><aside><b>Three useful reminders</b><ul>{a.tips.map(x=><li key={x}>{x}</li>)}</ul></aside></section><section className="areaLinks"><h2>Serving the Central Texas corridor</h2>{Object.entries(areas).filter(([s])=>s!==slug).map(([s,x])=><Link key={s} to={'/areas/'+s}>{x.city}<span>Explore →</span></Link>)}</section><section className="areaCta"><h2>Have a product question?</h2><p>Call the fictional demo number or return to the collection overview.</p><div className="actions"><a className="button" href={TEL}>Call us</a><Link className="textlink" to="/">View collection →</Link></div></section></main>}
function NotFound(){return <main className="notfound"><span>404</span><h1>This trail ends here.</h1><p>The page may have moved, but the Hill Country collection is right where you left it.</p><Link className="button" to="/">Return home</Link></main>}
function App(){return <BrowserRouter><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/areas/san-marcos" element={<Area slug="san-marcos"/>}/><Route path="/areas/kyle" element={<Area slug="kyle"/>}/><Route path="/areas/new-braunfels" element={<Area slug="new-braunfels"/>}/><Route path="*" element={<NotFound/>}/></Routes><Footer/><a className="mobilecall" href={TEL}>Call {PHONE}</a></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);